export const CURRENT_USER_KEY = '@STORAGE/CURRENT_USER';
export const USER_FRIEND_LIST_KEY = '@STORAGE/USER_FRIEND_LIST';
export const MESSAGE_RECENT_KEY = '@STORAGE/MESSAGE_RECENT';
export const MESSAGE_TOTAL_COUNT_KEY = '@STORAGE/MESSAGE_TOTAL_COUNT';
